network:
  ethernets:
    ens160:
      dhcp4: no
      addresses:
        - 10.0.0.152/24
      gateway4: 10.0.0.1
      nameservers:
          addresses: [8.8.8.8, 8.8.4.4]
    ens192:
      dhcp4: yes
      #$addresses:
      #  - 10.0.0.210/24
      #gateway4: 10.0.0.1
      #nameservers:
      #    addresses: [8.8.8.8, 8.8.4.4]
  version: 2